In [1]:
from sklearn.neighbors import KNeighborsClassifier
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score, confusion_matrix
import pandas as pd
import numpy as np

In [2]:
mtcars = pd.read_csv('mt_cars.csv')
mtcars.head()

Unnamed: 0   mpg  cyl   disp   hp  drat     wt   qsec  vs  am  gear  \
0          Mazda RX4  21.0    6  160.0  110  3.90  2.620  16.46   0   1     4   
1      Mazda RX4 Wag  21.0    6  160.0  110  3.90  2.875  17.02   0   1     4   
2         Datsun 710  22.8    4  108.0   93  3.85  2.320  18.61   1   1     4   
3     Hornet 4 Drive  21.4    6  258.0  110  3.08  3.215  19.44   1   0     3   
4  Hornet Sportabout  18.7    8  360.0  175  3.15  3.440  17.02   0   0     3   

   carb  
0     4  
1     4  
2     1  
3     1  
4     2

In [3]:
X = mtcars[['mpg','hp']].values
y = mtcars['cyl'].values

In [4]:
knn = KNeighborsClassifier(n_neighbors=3)
modelo = knn.fit(X,y)

In [5]:
modelo

KNeighborsClassifier(n_neighbors=3)

In [6]:
y_prev = modelo.predict(X)
print(y_prev)

[6 6 4 6 8 6 8 4 4 6 6 8 8 8 8 8 8 4 4 4 4 8 8 8 8 4 4 4 8 8 8 6]


In [7]:
accuracy = accuracy_score(y, y_prev)
precision = precision_score(y, y_prev, average='weighted')
recall = recall_score(y, y_prev, average='weighted')
f1 = f1_score(y, y_prev, average='weighted')
cm = confusion_matrix(y, y_prev)

print(f'Acurácia: {accuracy}, Precisão: {precision}, Recall: {recall}, F1: {f1}')
print('Matriz de confusão:\n', cm)

Acurácia: 0.9375, Precisão: 0.9395833333333333, Recall: 0.9375, F1: 0.9372947454844006
Matriz de confusão:
 [[10  1  0]
 [ 0  6  1]
 [ 0  0 14]]


In [8]:
#'mpg','hp'
new_data = np.array([[19.3,105]])

previsao = modelo.predict(new_data)
print(previsao)


distances, indices = modelo.kneighbors(new_data)
print(distances)
print(indices)

[6]
[[1.2        4.5177428  5.28109837]]
[[ 5 31  1]]


In [9]:
mtcars.loc[[1,5,31],["cyl","mpg","hp"]]

cyl   mpg   hp
1     6  21.0  110
5     6  18.1  105
31    4  21.4  109